### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by edgarwly** [haplotype/elai#1]
Hi, I have encountered a segmentation fault. Do you knnow how to solve it? Here is the log display:

./elai-lin -g aeth.txt -p 10 -g chry.txt -p 11 -pos pos.no.txt -o elai_out
##randseed = 1729080907
-warning: number of position files = 1
-warning: position files contain 22461434 records.
-warning: file 0 has 6 individual and 22461434 snps
-warning: file 1 has 6 individual and 22461434 snps
-warning: exclude 799 snps due to failure to match betweeen files.
number of individuals = 12
number of SNPs = 22460635
###m_morgan = 15.3138
-warning: read file 0 again
-warning: read file 1 again
-warning: total number of individuals = 12
0 0 0 0 0 0 0 0 0 0 0 0
nPanel = 12 ## nCohort = 0
Segmentation fault (core dumped)

The samples consist of two populations who are hybridizing, 6 individuals each.

Thank you for your help!

**Comment by haplotype** [comment]
you forgot the cohort. but even then it shouldn’t produce segmentation
fault.  is this non human data?  if you don’t mind, can you send a subset
of the data that can reproduce the error?

**Comment by edgarwly** [comment]
What if the source pop are also the admixed pop as there is introgression? Can the same genotype file twice but with different -p parameters? Yes, this is plant data. Here are a subset of the data:

[test_pos.txt](https://github.com/user-attachments/files/17395937/test_pos.txt)
[test_pop2.txt](https://github.com/user-attachments/files/17395939/test_pop2.txt)
[test_pop1.txt](https://github.com/user-attachments/files/17395940/test_pop1.txt)

**Comment by haplotype** [comment]
I can’t reproduce the segmentation error with the data you sent. It runs
with the command line you used. But produced nothing meaningful as there
are no cohorts. If your “references” are admixed, you can make do without
the reference. The following command line produce results that you may be
able to tell whether they are sensible or not.

../elai -g test_pop1.txt -p 1 -g test_pop2.txt -p 1 -C 2 -c 4 -o test -pos
test_pos.txt



The admixture output for 12 samples appear to agree with your
characterization that some samples are themselves admixed.



1.000 0.000

1.000 0.000

0.245 0.755

0.438 0.562

0.543 0.457

0.000 1.000

0.205 0.795

0.000 1.000

0.454 0.546

0.293 0.707

1.000 0.000

0.000 1.000

**Comment by edgarwly** [comment]
Thank you so much! It is working now after I added the cohort.

**Comment by edgarwly** [comment]
I have another question about the rows and columns of the admixture output. Using the results you posted, is the following interpretatino correct?

row 1-6 = 6 samples from pop1 (same order as test_pop1.txt)
row 7-12 = 6 samples from pop2 (same order as test_pop2.txt)
colulmn 1 = ancestry % from pop1
column 2 = ancestry % fro pop2

**Comment by haplotype** [comment]
yes, that’s correct.

**Comment by edgarwly** [comment]
Thanks!

**Comment by edgarwly** [comment]
Thanks!
